### МГУ им. М. В. Ломоносова
### Введение в анализ геоданных
#### [Материалы курса](https://github.com/keyonix/course_geodata)
## Python для анализа данных - Введение в обработку данных с Numpy и Pandas

### Numpy

**Numpy** фундаментальный пакет для научных вычислений в Python. Он предоставляет высокопроизводительный многомерный объект для массивов данных и инструменты для работы с ним.

In [1]:
import numpy as np

Массив в Numpy - это таблица значений одного типа. Количество измерений - ранг массива (rank). Размерность массива (shape) задана кортежем чисел, которые описывают размер каждого измерения массива.

Создавать массивы можно с помощью вложенных листов.

In [2]:
# Создадим массив ранга 1
a = np.array([1, 2, 3])  # создание массива из листа
print(a)                 # вывод
print(type(a))           # тип
print(a.shape)           # размерность массива

[1 2 3]
<class 'numpy.ndarray'>
(3,)


Получить доступ к элементам массива можно используя квадратные скобки.

In [3]:
print(a[0], a[1], a[2])   # вывод элементов массива
a[0] = 5                  # изменение элемента массива
print(a)                  # вывод массива

1 2 3
[5 2 3]


In [4]:
# Создадим массив ранга 2
b = np.array([[1,2,3],[4,5,6]])   # создание массива из вложенных листов
print(b)                          # вывод массива
print(b.shape)                    # вывод размерности массива
print(b[0, 0], b[0, 1], b[1, 0])  # вывод выбранных элементов массива

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


**ЗАДАНИЕ**<br>
Создайте массив из листа \[23,32,47,22\]. Измените значение второго элемента массива на значение 50. Выведите размерность массива.

In [5]:
# ВАШ КОД

#### Индексирование

По аналогии с листами, можно создавать срезы массива. Так как массивы могут быть многомерными, срез можно задать по каждому измерению.

In [6]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(a[1:,:])  # вывод среза массива

[[4 5 6]
 [7 8 9]]


In [8]:
print(a[:,:2])  # вывод среза массива

[[1 2]
 [4 5]
 [7 8]]


**ЗАДАНИЕ**<br>
Выведите срез массива *a*:

|||
|---|---|
|5|6|
|8|9|

In [9]:
# ВАШ КОД

#### Условное индексирование

Условное индексирование позволяет получать объекты массива, которые соответствуют заданному условию.

In [10]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
bool_ix = (a > 3)  # условное индексирование
print(bool_ix)     # вывод булева индекса

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [12]:
print(a[bool_ix]) # вывод элементов по булеву индексу

[4 5 6 7 8 9]


In [13]:
print(a[a > 3]) # условное индексирование с получение элементов массива

[4 5 6 7 8 9]


**ЗАДАНИЕ**<br>
Найдите элементы массива *a* со значениями больше 6 с помощью условного идексирования и выведите длину получившегося массива.

In [14]:
# ВАШ КОД

#### Базовые вычисления

In [15]:
# Создадим 2 массива содержащих числа с плавающей точкой
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [16]:
print(x)

[[ 1.  2.]
 [ 3.  4.]]


In [17]:
print(y)

[[ 5.  6.]
 [ 7.  8.]]


In [18]:
# Поэлементная сумма
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [19]:
# Поэлементное вычитание
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [20]:
# Поэлементное умножение
print(x * y)
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [21]:
# Поэлементное деление
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [22]:
# Поэлементное получение корня
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [23]:
# Матричное умножение
print(np.matmul(x,y))

[[ 19.  22.]
 [ 43.  50.]]


Numpy предоставляет большое количество функций для вычислений над массивами. Одна из наиболее используемых функция sum. Полный список функций детально представлен в [документации Numpy](#https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

In [24]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# Сумма всех элементов массива
print(np.sum(x))

45


In [26]:
# Сумма элементов по первой оси
print(np.sum(x, axis=0))

[12 15 18]


In [27]:
# Сумма элементов по второй оси
print(np.sum(x, axis=1))

[ 6 15 24]


**ЗАДАНИЕ**<br>
Посчитайте сумму значений больше 30 элементов массива, получившегося в результаты операции поэлементного умножения массива x на массив y. Воспользуйтесь операцией умножения массивов, условным индексированием и функцией суммирования элементов массива.

In [28]:
# ВАШ КОД

### Pandas

**Pandas** представляет собой легкую в использовании высокоуровневую структуру данных и многофункциональный инструмент для анализа данных. Полный функционал Pandas детально описан в [документации](https://pandas.pydata.org/pandas-docs/stable/).

In [29]:
import pandas as pd

Pandas имеет два основных объекта для хранения данных: Series и DataFrame. Series - вектор размерности 1, DataFrame - многомерный вектор. Оба объекта имеют индекс. Создадим pandas Series. При создании Series c помощью листа значений порядковый индекс создается автоматически.

In [30]:
s = pd.Series([1,3,5,np.nan,6,8]) # способ создания Series путем передачи листа значений

In [31]:
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [32]:
s.index  # объект индекса

RangeIndex(start=0, stop=6, step=1)

In [33]:
s.index.values # значения идекса

array([0, 1, 2, 3, 4, 5])

Библиотека Numpy обладает широким функционалом для работы с случайными величинами. Для демонстрации функционала Pandas создадим таблицу случайных значений с помощью Numpy. Далее создадим из данной таблицы Pandas DataFrame. При создание DataFrame можно явно передать название колонок в виде листа в параметр columns.

In [34]:
random_array = np.random.randn(6,4)  # создание таблицы случайных значений со стандартным нормальным распределением из 4 колонок и 6 строк

In [35]:
print(random_array)

[[ 1.64898127 -0.55278405 -0.24639225 -0.48135405]
 [ 1.70474864 -1.62226332  1.00405875 -0.20172524]
 [-0.06406074 -1.323426   -0.8950626   0.39950976]
 [ 0.70343895  0.62128933  1.53449612 -0.23578935]
 [ 0.39308724  0.50196034 -0.60621985 -1.13486565]
 [-0.16476231 -1.32932049  1.87372314 -0.53540099]]


In [36]:
df = pd.DataFrame(random_array, columns = ['A','B','C','D']) # создание DataFrame из Numpy array

In [37]:
df  # вывод DataFrame в табличном виде

A         B         C         D
0  1.648981 -0.552784 -0.246392 -0.481354
1  1.704749 -1.622263  1.004059 -0.201725
2 -0.064061 -1.323426 -0.895063  0.399510
3  0.703439  0.621289  1.534496 -0.235789
4  0.393087  0.501960 -0.606220 -1.134866
5 -0.164762 -1.329320  1.873723 -0.535401

In [38]:
df.head(3)  # вывод первых 3 значений DataFrame

A         B         C         D
0  1.648981 -0.552784 -0.246392 -0.481354
1  1.704749 -1.622263  1.004059 -0.201725
2 -0.064061 -1.323426 -0.895063  0.399510

In [39]:
df.tail(3)  # вывод последних 3 значений DataFrame

A         B         C         D
3  0.703439  0.621289  1.534496 -0.235789
4  0.393087  0.501960 -0.606220 -1.134866
5 -0.164762 -1.329320  1.873723 -0.535401

In [40]:
df.shape  # размерность DataFrame

(6, 4)

In [41]:
df.index.values  # значения идекса DataFrame

array([0, 1, 2, 3, 4, 5])

Для того чтобы получить быструю описательную статистику DataFrame можно воспользоваться функцие describe().

In [42]:
df.describe()  # описательная статистика DataFrame

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.703572 -0.617424  0.444101 -0.364938
std    0.816801  0.980464  1.176405  0.502613
min   -0.164762 -1.622263 -0.895063 -1.134866
25%    0.050226 -1.327847 -0.516263 -0.521889
50%    0.548263 -0.938105  0.378833 -0.358572
75%    1.412596  0.238274  1.401887 -0.210241
max    1.704749  0.621289  1.873723  0.399510

Функционал Pandas позволяет сортировать DataFrame как по индексу так и по определенной колонке.

In [43]:
df.sort_index(axis=1, ascending=False)  # сортировка по индексу

D         C         B         A
0 -0.481354 -0.246392 -0.552784  1.648981
1 -0.201725  1.004059 -1.622263  1.704749
2  0.399510 -0.895063 -1.323426 -0.064061
3 -0.235789  1.534496  0.621289  0.703439
4 -1.134866 -0.606220  0.501960  0.393087
5 -0.535401  1.873723 -1.329320 -0.164762

In [44]:
df.sort_values(by='B', ascending=False)  # сортировка по колонке

A         B         C         D
3  0.703439  0.621289  1.534496 -0.235789
4  0.393087  0.501960 -0.606220 -1.134866
0  1.648981 -0.552784 -0.246392 -0.481354
2 -0.064061 -1.323426 -0.895063  0.399510
5 -0.164762 -1.329320  1.873723 -0.535401
1  1.704749 -1.622263  1.004059 -0.201725

Pandas имеет широкий функционал для выделения и фильтрации данных.

In [45]:
df['C']  # выбор отдельной колонки

0   -0.246392
1    1.004059
2   -0.895063
3    1.534496
4   -0.606220
5    1.873723
Name: C, dtype: float64

In [46]:
df[2:4]  # срез данных по строкам

A         B         C         D
2 -0.064061 -1.323426 -0.895063  0.399510
3  0.703439  0.621289  1.534496 -0.235789

In [47]:
df.loc[3]  # выбор значений колонок для заданного значения индекса

A    0.703439
B    0.621289
C    1.534496
D   -0.235789
Name: 3, dtype: float64

In [48]:
df.loc[2:3,['A','B']]  # срез данных по строкам и колонкам

A         B
2 -0.064061 -1.323426
3  0.703439  0.621289

In [49]:
df.loc[2,'A']  # выбор значения DataFrame по индексу и колонке

-0.064060736040675179

Pandas включает функции для удобного условного индексирования.

In [50]:
df[df['A'] > 0]  # срез данных со значениями в колонке 'A' больше 0

A         B         C         D
0  1.648981 -0.552784 -0.246392 -0.481354
1  1.704749 -1.622263  1.004059 -0.201725
3  0.703439  0.621289  1.534496 -0.235789
4  0.393087  0.501960 -0.606220 -1.134866

In [51]:
df[(df['A'] > 0) & (df['B'] > 0)]  # срез данных со значениями в колонке 'A' и 'B' больше 0

A         B         C         D
3  0.703439  0.621289  1.534496 -0.235789
4  0.393087  0.501960 -0.606220 -1.134866

In [52]:
df[(df['A'] > 0) | (df['C'] > 0)]  # срез данных со значениями в колонке 'A' или 'C' больше 0

A         B         C         D
0  1.648981 -0.552784 -0.246392 -0.481354
1  1.704749 -1.622263  1.004059 -0.201725
3  0.703439  0.621289  1.534496 -0.235789
4  0.393087  0.501960 -0.606220 -1.134866
5 -0.164762 -1.329320  1.873723 -0.535401

**ЗАДАНИЕ**<br>
Выведите срез DataFrame df, в котором значения в колонке 'C' больше 0.2, значения в колонке 'D' меньше 0.9 и значения в колонке 'B' больше 0.

In [53]:
# ВАШ КОД

In [54]:
df['E'] = ['one', 'one','two','three','four','three']  # создание новой колонки со значениями в DataFrame

In [55]:
df[df['E'].isin(['two','four'])]  # срез данных со значениями в колонке 'E' равными 'two' и 'four'

A         B         C         D     E
2 -0.064061 -1.323426 -0.895063  0.399510   two
4  0.393087  0.501960 -0.606220 -1.134866  four

In [56]:
df.loc[df['A'] < 0.5, 'B'] = 0  # изменение значений DataFrame в колонке 'B' на значение 0 при условии, что значения в колонке 'A' меньше 0.5
df  # вывод DataFrame

A         B         C         D      E
0  1.648981 -0.552784 -0.246392 -0.481354    one
1  1.704749 -1.622263  1.004059 -0.201725    one
2 -0.064061  0.000000 -0.895063  0.399510    two
3  0.703439  0.621289  1.534496 -0.235789  three
4  0.393087  0.000000 -0.606220 -1.134866   four
5 -0.164762  0.000000  1.873723 -0.535401  three

**ЗАДАНИЕ**<br>
Изменените значений DataFrame df в колонке 'D' на значение 0.5 при условии, что значения в колонке 'D' меньше 0.5 или значения в колонке 'C' меньше 0.5.

In [57]:
# ВАШ КОД

In [58]:
df['F'] = [0.2, np.NaN, 0.5, 0.1, np.NaN, np.NaN]  # создание колонки с неизвестными значениями
df  # вывод DataFrame

A         B         C         D      E    F
0  1.648981 -0.552784 -0.246392 -0.481354    one  0.2
1  1.704749 -1.622263  1.004059 -0.201725    one  NaN
2 -0.064061  0.000000 -0.895063  0.399510    two  0.5
3  0.703439  0.621289  1.534496 -0.235789  three  0.1
4  0.393087  0.000000 -0.606220 -1.134866   four  NaN
5 -0.164762  0.000000  1.873723 -0.535401  three  NaN

In [59]:
df.dropna()  # удалить все строки в DataFrame, которые зодержат неизвестные значения

A         B         C         D      E    F
0  1.648981 -0.552784 -0.246392 -0.481354    one  0.2
2 -0.064061  0.000000 -0.895063  0.399510    two  0.5
3  0.703439  0.621289  1.534496 -0.235789  three  0.1

In [60]:
df.fillna(value=5)  # заменить все неизвестные значения на значение 5

A         B         C         D      E    F
0  1.648981 -0.552784 -0.246392 -0.481354    one  0.2
1  1.704749 -1.622263  1.004059 -0.201725    one  5.0
2 -0.064061  0.000000 -0.895063  0.399510    two  0.5
3  0.703439  0.621289  1.534496 -0.235789  three  0.1
4  0.393087  0.000000 -0.606220 -1.134866   four  5.0
5 -0.164762  0.000000  1.873723 -0.535401  three  5.0

Pandas обладает функциями для вычисления различных статистических показателей.

In [61]:
print(df['A'].mean())  # среднее
print(df['A'].std())  # стандартное отклонение
print(df['A'].sum())  # сумма

0.7035721752845528
0.8168009108509557
4.221433051707317


In [62]:
df.groupby('E').mean()  # получение статистических показателей с групировкой по категориальной колонке

A         B         C         D    F
E                                                 
four   0.393087  0.000000 -0.606220 -1.134866  NaN
one    1.676865 -1.087524  0.378833 -0.341540  0.2
three  0.269338  0.310645  1.704110 -0.385595  0.1
two   -0.064061  0.000000 -0.895063  0.399510  0.5

In [63]:
df.groupby('E').agg(['sum', 'std', 'mean']) # получение нескольких статистических показателей с групировкой по категориальной колонке

A                             B                             C  \
            sum       std      mean       sum       std      mean       sum   
E                                                                             
four   0.393087       NaN  0.393087  0.000000       NaN  0.000000 -0.606220   
one    3.353730  0.039433  1.676865 -2.175047  0.756236 -1.087524  0.757666   
three  0.538677  0.613911  0.269338  0.621289  0.439318  0.310645  3.408219   
two   -0.064061       NaN -0.064061  0.000000       NaN  0.000000 -0.895063   

                                  D                        F           
            std      mean       sum       std      mean  sum std mean  
E                                                                      
four        NaN -0.606220 -1.134866       NaN -1.134866  NaN NaN  NaN  
one    0.884202  0.378833 -0.683079  0.197727 -0.341540  0.2 NaN  0.2  
three  0.239870  1.704110 -0.771190  0.211857 -0.385595  0.1 NaN  0.1  
two         NaN -0.895063  0.399510       NaN  0.399510  0.5 NaN  0.5

**ЗАДАНИЕ**<br>
Выведите сумму значений колонок в DataFrame df с группировкой по категориальной колонке 'E' для среза df, в котором значения в колонке 'C' больше, чем среднее значение в колонке 'A'.

In [64]:
# ВАШ КОД